version: "3"

server:
  command: "php public/index.php"
  env:
    - APP_RUNTIME: Vanta\Integration\Symfony\Temporal\Runtime\TemporalRuntime

rpc:
  listen: tcp://0.0.0.0:6001

temporal:
  address: "0.0.0.0:7233"
  activities:
    num_workers: 1

logs:
  level: debug
  channels:
    temporal.level: error



kv:
  test:
    driver: memory
    config:
      interval: 10