name: Stats-Analysis CI
on: [ push, pull_request ]

jobs:
  stats-analysis:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [ 8.2, 8.3 ]
    steps:
      - uses: actions/checkout@v3.3.0

      - name: Install Infrastructure
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer:v2
          coverage: none


      - name: Start stats-analysis
        uses: ramsey/composer-install@v2
        with:
          composer-options: --optimize-autoloader
      - run: vendor/bin/phpstan --error-format=github